[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# This ensures Next.js works properly on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"
